# Generated by Django 3.1.7 on 2021-07-27 15:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hedding', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=1000)),
                ('auther', models.CharField(max_length=100)),
                ('date', models.DateTimeField(default=datetime.date(2021, 7, 27))),
                ('img', models.ImageField(blank=True, upload_to='images')),
            ],
        ),
    ]
